### ISSUE TITLE
Timer starts at 1:29 on Android devices

### ISSUE THREAD

**Issue by SebastianSchultz** [kimai/kimai-mobile#10]
Hello,

I think I've found a little bug in Kimai Mobile.
When I start a timer on my iPad 4 everything works fine and the timer starts at 0:00.
When I start a timer on my Samsung Galaxy S5 (Android device) the timer starts always at 1:29.
But at the Kimai Site the timer is correct.

How can I solve this?!

**Comment by SMundt** [comment]
Hmm, is there any possibility to set the timer always to 0:00 when I click on the start button?

**Comment by SMundt** [comment]
Does no one has an idea?

**Comment by simonschaufi** [comment]
Will test it
