### ISSUE TITLE
auto-login

### ISSUE THREAD

**Issue by simonschaufi** [kimai/kimai-mobile#14]
_From @tk2016 on March 13, 2016 14:52_

I am a new user kimai and the program works fine . The problem is the mobile version , I must log in again and again. Is it possible to introduce auto-login ? Auto -login works fine in the desktop version but not in the mobile version. 

_Copied from original issue: kimai/kimai#613_

**Comment by himmelbuerger** [comment]
I added to my local version that I can autologin through the android application by using the POST data.
I tried to push it back but got a 403. How can I contribute? (first time on github :-) )

**Comment by kevinpapst** [comment]
closed with #613
