### ISSUE TITLE
invisible projects show in main menu

### ISSUE THREAD

**Issue by piflixe** [kimai/kimai-mobile#15]
I am testing the mobile frontend on our new kimai v0.9.3.1387 installation. I have the problem that a whole lot of projects show in the main menu, even though they are set to "invisible" in the admin panel. They are projects that have long been finished, that's why we set them to invisible. 

I guess there will be a whole lot of invisible projects accumulating over time so it would be nice just to see the active "visible" projects.

**Comment by kevinpapst** [comment]
Thanks for testing and another bug report :)
There is a new pull request that should fix your issue: https://github.com/kimai/kimai/pull/723

**Comment by kevinpapst** [comment]
Fixed in Kimais develop branch and will be included in the next release

**Comment by piflixe** [comment]
I tested the changes #723. Works for me. Thanks for your work!

**Comment by kevinpapst** [comment]
Hey :) and thanks for your feedback!
