### ISSUE TITLE
Unable to log on

### ISSUE THREAD

**Issue by Geo-Ron** [kimai/kimai-mobile#23]
Hi all,

First I would like to thank you for this addon. It looks promising.
I downloaded the source and placed it in a subfolder 'mobile'.

But when I try to log on, nothing happens...

Not with a local account, nor with the LDAP account...

I am unable to find any logging.

My host is Windows IIS, with PHP 5.6.30

**Comment by simonschaufi** [comment]
The only thing you need to adjust is this line: https://github.com/kimai/kimai-mobile/blob/master/index.php#L22

Apart from that, I have no experience with IIS as we always use apache or nginx.

**Comment by Geo-Ron** [comment]
I saw this line. Remarks mentions it only should be changed if the folder was not a subfolder.

Anyhow, changed it to the url of my kimai installation, but still a no-go.
Still no reaction from the interface when you try to log on. No error, nothing.
