### ISSUE TITLE
Main Link broken https://www.kimai.org/kimai-mobile/

### ISSUE THREAD

**Issue by friedger** [kimai/kimai-mobile#25]
https://www.kimai.org/kimai-mobile/ leads to 404

**Comment by kevinpapst** [comment]
Thanks for the info, I deleted the link!
I guess this page never existed, don't know why the link was added in the first place...

**Comment by simonschaufi** [comment]
> I guess this page never existed

It did. We had a special landing page for the mobile version

**Comment by kevinpapst** [comment]
Really? Can you remember what it was, where did it come from? Was ist just the README from this repository?

**Comment by kevinpapst** [comment]
Okay, found it: https://github.com/kimai/kimai-mobile/tree/gh-pages
Will integrate it this weekend ... hopefully

**Comment by kevinpapst** [comment]
Thanks @friedger for the info, I re-added the page to our website: 
https://www.kimai.org/kimai-mobile/
